apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptos-django
spec:
  replicas: 2  # One replica for development
  selector:
    matchLabels:
      app: cryptos-django
  template:
    metadata:
      labels:
        app: cryptos-django
    spec:
      containers:
      - name: cryptos-django
        image: aniketrath/cryptos-backend  # Use the provided Docker image
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: cryptos-django-service
spec:
  type: NodePort
  selector:
    app: cryptos-django
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
    nodePort: 30002  # Custom port for accessing the app
