# Generated by Django 4.2.13 on 2024-05-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoinID', models.CharField(max_length=100, null=True)),
                ('Symbol', models.CharField(max_length=100, null=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Volume', models.DecimalField(decimal_places=4, max_digits=100, null=True)),
                ('PercentChange', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
            ],
        ),
    ]
