# Generated by Django 4.2.13 on 2024-05-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchforeignapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coindata',
            name='Price',
            field=models.DecimalField(decimal_places=4, max_digits=100, null=True),
        ),
    ]
