# Generated by Django 4.2.13 on 2024-05-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetchforeignapi', '0002_coindata_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coindata',
            old_name='Price',
            new_name='Price_ATH',
        ),
    ]
